### ISSUE TITLE
Add an editable configuration file for game command-lines and other things

### ISSUE THREAD

**Issue by rglx** [RobertZenz/EasyMineLauncher#10]
I would use this a lot more if you could set the command-line for the game, and how the custom authorization part gets the login tokens (the URL that the launcher fetches, and how it splits and returns them), and other things that the game environment might need (like executing a shell/batch script, that kind of stuff.)

**Comment by RobertZenz** [comment]
Can you please clarify what you mean? I've always had the thought about creating a configuration file, but always decided against it because there's no difference between writing the configuration file and writing a launcher/shell script with all the needed parameters.

I've also exposed as many settings/variables I could, there's pretty much nothing left to expose in the process (might not be true, 0.17 is refactored to use MMK, so I might still find stuff I can expose now...reminds me, I _did_ want to add something else, can't remember what, though) of authentication.

Anyway, what options would you like to see added?

**Comment by rglx** [comment]
Well, let's say your game's launch parameters needed to specify a different
main class, or some additional JARs, or just a 1.6 JAR (which uses like 4
extra commandline arguments (--assetsdir, --gamedir, a couple others, I
think.), you could add them, and have the game work properly. (The game
handles all the loading and directory changes in 1.6) The only issue might
be getting authorization data, unless they didn't change it too much, or if
pre-1.5 authorization still works and can be used. An example configuration
file might be found in the JAR's directory or just have it specifiable by a
switch, and have all of the settable options in there.

**Comment by RobertZenz** [comment]
First of all, EML will never work with 1.6 and above, that's what EML2 will be for. There is just too much changed stuff in there.

I'm sorry I still don't see how this helps. You can always get all the existing parameters with `--help` and examples are here in the README. There is no difference between writing

```
java -jar EasyMineLauncher.jar \
    --username=USERNAME \
    --password=WHOOP \
    --authentication
```

or

```
username=USERNAME
password=WHOOP
authentication
```

and

```
java -jar EasyMineLauncher.jar --config=yourfile.config
```

except that you now have one extra file laying around.

Or do you mean that you want to be able to select a configuration during launch?
