### ISSUE TITLE
Include Mojang authentication

### ISSUE THREAD

**Issue by ghost** [RobertZenz/EasyMineLauncher#3]
Requesting support to prompt for username/password on startup which will then pass to Mojang; see SKMC Launcher for example:

https://github.com/sk89q/skmclauncher/blob/master/src/main/java/com/sk89q/mclauncher/LoginSession.java

**Comment by RobertZenz** [comment]
Prompting for something is exactly what this launcher is _not_ about.

Though, I already thought about including the authentication, but so far opted against it as I did not see need for it. I will think about it.

**Comment by RobertZenz** [comment]
Also note that the skmclauncher code is licensed under GPLv3, while EasyMineLauncher is BSD, so I would not be able to use _any_ code from skmc. GPLv3 does require that _everything_ in the project is also licensed under GPL.

I will also not relicense EML to a compatible license because I don't feel comfortable licensing this code under anything more restricting (it is very generic after all and interfaces with something closed source).

But as I said, I will think about it.

**Comment by RobertZenz** [comment]
Actually, after figuring some things out, I've started to work on this. Expect it in 0.13...most likely next week or so.

**Comment by RobertZenz** [comment]
As a matter of fact, I found right now the time to finish this. v0.13 is ready to download.
